version: '2'
services:
    1try-app:
        image: 1try
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://1try-mysql:3306/1try?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    1try-mysql:
        extends:
            file: mysql.yml
            service: 1try-mysql
